---
title: "Jain"
author: "Khushi Jain"
format: html
editor: visual
---

Configuration

```{r}
#| message: false
library(here)
here::i_am("systems.Rproj")
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
```

## Main data set import

### Q1 
Added data file and committed it. 

### Q2 Git

Git-hub Project: [systems](https://github.com/khushiijain/systems)

### Q3 Load Data

```{r}
#| message: false
#| warning: false
systems <- vroom(here("data", "All-systems.csv"), locale = locale(decimal_mark = "."))
```

### 4 Data Description
```{r}
# Findind variables with missing values
vars_with_na <- colnames(systems)[colSums(is.na(systems)) > 0]

#Final Table
kable(systems |> summarise(
  `Number of Observations` = nrow(systems),
  `Number of variables` = ncol(systems),
  `Number of Missing values for RELATIVE RADIUS` = sum(is.na(`RELATIVE RADIUS`)),
  `Number of Missing values for Effective Temperature` = sum(is.na(`Effective Temperature`)),
  `Number of Missing values for star luminosity` = sum(is.na(`star luminosity`)),
  `Number of observations with at least one missing value` = systems |>
    mutate(across(everything(), is.na)) |>
    rowwise() |>
    sum(TRUE)
  ))
```

##  Introductory analysis

### 5 Graphical Representation
```{r}
systems |>
  filter(!is.na(`Effective Temperature`)) |>
  filter(!is.na(`Star Mass`)) |>
  ggplot(aes(x=`Effective Temperature`, y=`Star Mass`)) +
  geom_col()+
  labs(title = "Mass of a star as a function of its temperature")
```
### 6 Extreme Stars

```{r}
#table with numerical variables
long_table <- systems %>%
  pivot_longer(cols = c(`Star Mass`, Distance, `Effective Temperature`, `RELATIVE RADIUS`, `star luminosity`)) |>
  group_by(name)
```

```{r}
#extreme minimum and maximum
long_min <- long_table |> slice_min(value) 
long_max <- long_table |> slice_max(value)
```

```{r}
kable(extreme_stars <- long_max |>
  full_join(long_min, by = join_by(STAR_NAME, star_key, `TYPE OF STAR`, name, value)))
```

### Q7 New data files
```{r}
#| message: false
#| warning: false
factions_battletech <- vroom(here("data", "bt+factions.csv"), na = "unknown")
factions_control <- vroom(here("data", "BT-FACTION-SYSTEM.csv"), na = "unknown")
```

### Q8-9 Star systems in 2821

```{r}
kable(factions_control |> summarise(
  `Number of Abandoned star systems` = sum(`DETAILED STRUCTURE` == "A"), 
  `Number of Independent star systems` = sum(`DETAILED STRUCTURE` == "I"),
  `Number of Undiscovered star systems` = sum(`DETAILED STRUCTURE` == "U")
  ),
  caption = "Star systems in 2821"
)
```


